
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/ia_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
#   启动时是否执行初始化 sql：always 执行/never 不执行
    initialization-mode: never
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
#     启动时是否新建表格 update：只更新
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
